name: badger-test-env
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl
  - scikit-learn ==0.24
  - pyepics ==3.5
  - tensorflow ==2.4
  - xopt ==0.5
  - python ==3.7
  - pip:
    - badger-opt==0.4
    - bayesian-optimization ==1.2
