name: badger-test-env
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn ==0.23.2
  - pyepics ==3.5.0
  - tensorflow ==2.6.0
  - xopt ==0.5.0
  - bayesian-optimization ==1.2.0
  - python ==3.7
  - pip:
    - badger-opt==0.4
