name: badger-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn=0.23.2
  - xopt
  - bayesian-optimization
  - pyepics
  - qt=5.12.5
  - badger-opt=0.6.0
  - pytest
  - pytest-qt
